NormalNvim/NormalNvim

lua/base/utils/status/component.lua
lua/base/utils/status/condition.lua

I will make this patch more beautiful later, but for not it does what it is supposed to do. If a file don't have a filetype, it won't try to show the lsp status on the status bar anymore.

Hotfix(empty buffer)

---

lua/plugins/2-ui.lua

Actually, with 634af9c05cd53c2424192ad22219e4316b623ed1 we can use BufEnter instead of VeryLazy, which prevents heirline to load slightly slower in those border case scenarios. Thank you mehalter from AstroNvim for coming up with the improvement.

improvement(heirlne) 

---

README.md

neural use env var $OPENAI_API_KEY instead of $CHATGPT_API_KEY check (https://github.com/dense-analysis/neural) therefore I fix command and few URLs that will make it easy for user to use Ask chatgpt function.

fix wrong how to use AI command in README.md

---

lua/lazy_snapshot.lua

* lsp-timeout was failing for neovim versions lower than 0.10.  This should allow it to run on ^0.9
* Also fixes border case scenarios.

Freeze plugin versions → lsp-timeout fixes

---

README.md

I noticed while navigating the documentation that some links were redirecting to a fork instead of the main repository. This PR addresses this issue by updating the links to point to the main repository.

docs: update documentation links

---

lua/plugins/3-dev-core.lua

from 5 minutes to 10 before triggering.

♻️refactor(garbage-day.nvim): Let's make it a bit less aggresive.

---

lua/lazy_snapshot.lua

Was reviewing the repo and came across a duplicate in `lazy_snapshot.lua`.
Making this PR to fix it.

Remove duplicate entry from Lazy

---

lua/base/4-mappings.lua
lua/base/utils/lsp.lua
lua/lazy_snapshot.lua
lua/plugins/1-base-behaviors.lua

* `:NvimUpdateConfig` renamed to `NvimDistroUpdate`.
* `:NvimReload` removed, as it is now automatically managed by the option `hot_reload_files`.

`distroupdate.nvim` updated to `v0.4.0`.

---

lua/plugins/3-dev-core.lua

This is mandatory for the new none-ls version.

♻️refactor(bash): shellcheck is now provided by bashls.

---

lua/base/utils/lsp.lua
lua/plugins/3-dev-core.lua

* This new config is valid with both the old and the new version.
* We are not shipping the new none-ls version yet though. Let's give it a a few weeks so people have time to fix possible bugs, as they just went through a massive refactor.

This PR preprares none-ls for its new version

---

.selene-schema.yml
lua/base/utils/lsp.lua

This is a minor fix that affect mostly to the yamlls fix we were supposed to be applying.
After this commit, the yamlls lsp server won't show warnings anymore.

fix(lsp): User lsp settings capabilities are now correctly applyed

---

lua/plugins/4-dev.lua

This improves the way luasnip work.

🐛fix(`luasnip`): Now install jsregexp correctly on UNIX.

---

lua/plugins/2-ui.lua

🐛fix(`:CoverageSummary`): Don't show `mini-indent.nvim` anymore.

---

lua/base/4-mappings.lua
lua/base/utils/ui.lua
lua/plugins/4-dev.lua

* It marks the lines of the current buffer that are not covered by tests yet.
* This makes super easy to figure out the lines where you are missing code coverage in your code.

✨feat(nvim-coverage): New mapping Space + T + C to toggle code coverage signs.

---

lua/lazy_snapshot.lua

The merit on this one is for Steve for looking into it.

fix(aerial): Window now open correctly even when the cursor is over Neotree, or any nofile buftype. 

---

lua/base/1-options.lua
lua/plugins/2-ui.lua

We forgot to delele `lib.component.compiler_build_type()` from the inactive winbar. So it was displaying in border cases in C and Java.
There is a 99% chance you never encountered this bug, but it's gone now anyway.

fix(heirline `lib.component.compiler_build_type()`): displaying on neotree/terminal/telescope

---

lua/base/4-mappings.lua
lua/plugins/2-ui.lua

This is good for people who prefer to install NormalNvim manually by cloning.

🐛fix(yazi): Don't create yazi keymappings is yazi is not installed.

---

lua/lazy_snapshot.lua
lua/plugins/1-base-behaviors.lua
lua/plugins/3-dev-core.lua

…as it is esentially HTML support for the plugin `autopairs`.
Also, we now use the correct lazy event.

♻️fix(`nvim-ts-autopairs`): Has been moved to `1-base-behaviors.lua`

---

lua/plugins/1-base-behaviors.lua

In https://github.com/mikavilpas/yazi.nvim/pull/320, the commands were changed to scoped commands starting with `Yazi`. This commit updates the commands in the base behaviors plugin to use the new commands.

fix(yazi): use new yazi commands

---

lua/base/3-autocmds.lua
lua/plugins/3-dev-core.lua
lua/plugins/4-dev.lua

Nvim 0.9 legacy code was already removed in previous versions. This is just a line we forgot to delete.

♻️refactor(comments): Replace all `vim.loop` by `vim.uv`.

---

lua/base/4-mappings.lua

Since I was on it, I've refactored the code to make it easier to read.

🐛fix(vim.g.autoformat_enabled): Work correctly again.

---

lua/base/3-autocmds.lua

Because we already have a button for the compiler on the UI, there is no point in having another shortcut on the right click.

refactor: Remove `Start Compiler`. Add `Format Code`.

---

lua/plugins/2-ui.lua

From now on we use `vim.hl` instead.

♻️refactor(`vim.highlight`): is going to be deprecated.

---

lua/plugins/3-dev-core.lua

Otherwise the mason regristries directory might not be created correctly.

fixn(vim-java): order seem to matter now for mason registries.

---

lua/base/4-mappings.lua

The `filetype` option is buffer local, so we should omit the win option.

fix(mappings): can't open home page when more than one window opened
