- lua/base/4-mappings.lua
Also allow it in visual mode, in case the user prefers it over ctrl+a
> fix(improved gg)

- .gitignore
- lua/plugins/1-base-behaviors.lua
See PRs [134](https://github.com/nvim-pack/nvim-spectre/pull/134) [135](https://github.com/nvim-pack/nvim-spectre/pull/135) [136](https://github.com/nvim-pack/nvim-spectre/pull/136) [137](https://github.com/nvim-pack/nvim-spectre/pull/137)
> feat(spectre) Fixed the project to prevent users from breaking the UI

- lua/base/1-options.lua
- lua/plugins/1-base-behaviors.lua
This will appear in the spectre ? manual.
> chore(spectre): Added mappings - Insert for qwerty and colemak.

- lua/plugins/4-dev.lua
Useful once the PR #318 is accepted:
https://github.com/rafamadriz/friendly-snippets/pull/318
> feat(friendly-snippets) added rustdoc

- lua/plugins/1-base-behaviors.lua
We already had space+fb to toggle. But let's also have 'q' as it is what most people expect it to be.
> chore(spectre) q to quit

- lua/base/1-options.lua
- lua/base/4-mappings.lua
- lua/base/utils/lsp.lua
- lua/base/utils/ui.lua
for nvim 0.10+ (enabled by default).
* We've also improved inlay hints allowing the user to enable/disable globally or per buffer by pressing <leader>ui
> feat(semantic highlighting) New option for better code highlinging 

- lua/base/utils/git.lua
It was provoking an error. Now it works as it should.
> fix(command) :NvimChangelog

- lua/base/utils/buffer.lua
- lua/lazy_snapshot.lua
- lua/plugins/0-dependencies.lua
On choosing what wintab to show when a buffer is wiped/deleted. This change come from upstream.
> feat(mini.bufremove) This plugin is smarter 

- lua/base/utils/status/component.lua
- lua/plugins/2-ui.lua
We also teach users how to create custom components.
> feat(heirline) Component 'encoding' is now easy to enable.

- lua/base/utils/status/component.lua
- lua/base/utils/status/provider.lua
- lua/plugins/2-ui.lua
A spinner will show on the status bar while a progam is compiling.
> feat(heirline) New compiler component.

- lua/base/utils/init.lua
- lua/plugins/2-ui.lua
- lua/plugins/3-dev-core.lua
This has reduced startup time too!
> chore(lspconfig): Updated from upstream.

- lua/base/4-mappings.lua
- lua/plugins/2-ui.lua
This is just a minor cleanup over `v3.3.13`. It doesn't fix or break anything.
> 100% Irrelevant stuff

- README.md
- lua/base/1-options.lua
- lua/base/3-autocmds.lua
- lua/base/4-mappings.lua
- lua/base/health.lua
- lua/base/utils/lsp.lua
- lua/plugins/1-base-behaviors.lua
- lua/plugins/4-dev.lua
Hi, 👋.
I found many typos in this repository, thanks to [crate-ci/typos](https://github.com/crate-ci/typos).
You can run locally using the CLI app and in the CI using its Github action.
Thank you for creating a Neovim distro with Colemak keybindings 🎖️
> refactor: fix typos

- lua/base/utils/init.lua
- lua/plugins/2-ui.lua
Don't be in a hurry to update, because I might cleanup a bit more, and no behaviors have been changed since `v3.5.7`.
From now on, 99% of bugfixes are gonna come from plugin updates, so do `<Space>pU` if you have installed NormalNvim in the last 24h and encountered any bug.
> Cleanup in `base.utils` and the plugin `heirline`.

- lua/base/3-autocmds.lua
- lua/base/utils/buffer.lua
- lua/base/utils/init.lua
- lua/lazy_snapshot.lua
- lua/plugins/2-ui.lua
- lua/plugins/3-dev-core.lua
This PR reduces the amount of lines of the heirline plugin from 300 to 60, by moving internal logic to the plugin `heirline-components.nvim`.
closes #301
> Heirline refactor - Non breaking, no behavioral changes.

- lua/base/4-mappings.lua
- lua/lazy_snapshot.lua
- lua/plugins/1-base-behaviors.lua
- lua/plugins/3-dev-core.lua
Which is semantically meaningful.
> breaking!: Distro update commands now have the prefix `Distro`.

- lua/plugins/1-base-behaviors.lua
- lua/plugins/2-ui.lua
- lua/plugins/4-dev.lua
This version brings a new winbar.
If you don't like it you can still use your old config and it will look as classic NormalNvim.
> ✨feat(heirline-components): New winbar

- lua/base/3-autocmds.lua
- lua/plugins/3-dev-core.lua
- lua/plugins/4-dev.lua
It wasn't starting as expecting due to a regression.
> fix(nvim-java): DAP

- lua/base/utils/lsp.lua
- lua/plugins/1-base-behaviors.lua
- lua/plugins/2-ui.lua
- lua/plugins/3-dev-core.lua
- lua/plugins/4-dev.lua
A couple lines are more obvious and maintainable now.
> minor refactor

- lua/lazy_snapshot.lua
With support for lua and ruby.
> ✨feat(`dooku.nvim`): New major version released.

- lua/base/1-options.lua
- lua/base/4-mappings.lua
- lua/base/utils/init.lua
- lua/plugins/1-base-behaviors.lua
- lua/plugins/2-ui.lua
- lua/plugins/4-dev.lua
By pressing Space + Dd three times.
> v3.8.0 plugins + NormalNvim can now generate its own html documentation

- lua/plugins/3-dev-core.lua
So let's use it instead to save some code.
> refactor: Folke has just released a plugin with the TSX comments hack.

- lua/base/4-mappings.lua
- lua/plugins/3-dev-core.lua
Fixes:
* Code actions not displaying.
* Debugger not starting correctly.
> fix(java-nvim): We patch some regressions in the plugin

- lua/lazy_snapshot.lua
Hopefuly this will be merged and we won't have to maintain a fork.
> fix(overseer): correct commit to enable group_potition.

- lua/lazy_snapshot.lua
This is gonna be a requirement for the next overseer version.
> chore(dap): version updated to latest commit.

- lua/base/2-lazy.lua
- lua/plugins/1-base-behaviors.lua
- lua/plugins/2-ui.lua
- lua/plugins/4-dev.lua
on lazy → https://github.com/folke/lazy.nvim/commit/a089d43dba7438532c56e1c582c5974713bd48f8
> fix(luarocks): No need for this fix anymore as folke has fixed it

- lua/base/4-mappings.lua
- lua/lazy_snapshot.lua
- lua/plugins/2-ui.lua
The PR in question: https://github.com/mikavilpas/yazi.nvim/pull/320
> ♻️refactor(Yazi.nvim): Our PR has been merged so we an use the commands now.

- lua/base/4-mappings.lua
Fix debugger's "step out" key map
> Fix debugger's "step out" key map

- lua/base/2-lazy.lua
This should make easier to understand what every block of code does.
> refactor(`2-lazy.lua`): Code is now divided in functions we call at the end of the file.

- lua/base/4-mappings.lua
These are also defined on lines `480` - `487`.
> Remove duplicate <S-Down> and <S-Up> mappings

- lua/base/4-mappings.lua
- lua/base/utils/lsp.lua
- lua/plugins/3-dev-core.lua
If you find any issue, update to Neovim 0.11
> Nvim 0.11 deprecations removed
